runtime: python39
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

libraries:
- name: flask
  version: "1.1"
- name: opencv-python-headless
  version: "4.5.1"
- name: ultralytics
  version: "latest"
- name: werkzeug
  version: "2.0.2"

env_variables:
  PYTHONUNBUFFERED: "1"

entrypoint: gunicorn -b :$PORT auto:app
